### ISSUE TITLE
llvmtcl fails to build on Ubuntu Yakkety, gcc 6.3, llvm 4.0

### ISSUE THREAD

**Issue by kennykb** [dkfellows/llvmtcl#2]
The latest master of llvmtcl fails to build on Ubuntu Yakkety, with gcc 6.3.0 and llvm 4.0.
Error message is: 

```
../llvmtcl/generic/debuginfo.cpp: In function ‘int DefineArrayType(ClientData, Tcl_Interp*, int, Tcl_Obj* const*)’:
../llvmtcl/generic/debuginfo.cpp:669:74: error: ‘NBBY’ was not declared in this scope
     auto val = builder->createArrayType(cnt * sz, ALIGN_SIZE(cnt * sz) * NBBY,
                                                                          ^~~~

```
NBBY is defined in sys/param.h, which nothing includes. That said, it appears that in this case the purpose would be to use the standard CHAR_BIT instead.  The attached patch compiles successfully (albeit with a lot of warnings) and appears to work (at least, it runs the demo suite).

[llvmtcl.patch.txt](https://github.com/dkfellows/llvmtcl/files/1066731/llvmtcl.patch.txt)

**Comment by dkfellows** [comment]
Thanks!
